apiVersion: apps/v1
kind: Deployment
metadata:
  name: pbx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pbx
  template:
    metadata:
      labels:
        app: pbx
    spec:
      containers:
      - name: pbx
        image: 3cxphonecluster/3cximage01
        ports:
        - name: api
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: pbx
spec:
  type: LoadBalancer
  selector:
    app: pbx
  ports:
  - port: 5000
    name: api
