apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pbx-deployment
spec:
  selector:
    matchLabels:
      app: pbx
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: pbx
    spec:
      containers:
      - name: pbx
        image: 3cxphonecluster/image01:latest
        ports:
        - containerPort: 3015
        - containerPort: 3001
        - containerPort: 443
        - containerPort: 5060
        - containerPort: 5061
        - containerPort: 5090
        - containerPort: 9000
        - containerPort: 9001
        volumeMounts:
        - mountPath: /mnt/backup
          name: backup-disk
        - mountPath: /mnt/recordings
          name: recording-disk
        - mountPath: /var/log
          name: log-disk
      volumes:
      - name: backup-disk
      - name: recording-disk
      - name: log-disk
