apiVersion: v1
kind: Service
metadata:
  name: pbx-deployment
spec:
  selector:
    app: pbx
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort:  30000
    type: NodePort
