apiVersion: v1
kind: Service
metadata: 
  name: pbx-access-services
  labels: 
    name: pbx-access-service
spec: 
  type: LoadBalancer
  ports:
  - name: threecx-pbx-advanced-access
    port: 5001
    targetPort: 5001
  - name: threecx-pbx-basic-access1
    port: 5015
    targetPort: 5015
  - name: threecx-pbx-basic-access2
    port: 443
    targetPort: 443
  - name: threecx-pbx-sip-rn
    port: 5060
    targetPort: 5060
  - name: threecx-pbx-sec-sip-rn
    port: 5061
    targetPort: 5061
  - name: threecx-pbx-tunnel
    port: 5090
    targetPort: 5090
  - name: threecx-pbx-mediaserver9000
    port: 9000
    targetPort: 9000
  - name: threecx-pbx-mediaserver9001
    port: 9001
    targetPort: 9001
  selector: 
    name: pbx-deployment
